name: Run Postman tests

on: 
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 7 */2 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Newman + Allure reporter
        run: npm install -g newman newman-reporter-allure

      - name: Run live collection (dictionaries, areas)
        run: |
          newman run ./collections/hh-live.postman_collection.json \
          -e ./environment/api.hh.ru.postman_environment.json \
            --reporters cli,allure \
            --reporter-allure-resultsDir allure-results

      - name: Run mocked collection (vacancies)
        if: always()
        run: |
          newman run ./collections/hh-vacancies-mocked.postman_collection.json \
            -e ./environment/api.hh.ru.postman_environment.json \
            --reporters cli,allure \
            --reporter-allure-resultsDir allure-results
            

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report
          keep_reports: 20

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publush_branch: gh-pages
          publish_dir: allure-report

      - name: Telegram Notification
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🥶🥶🥶 HH Tests
            
            📊 Статус: ${{ job.status }}
            🔗 Репо: ${{ github.repository }}
            
            📈 Allure:
            https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
